export const questionUrl = '/api/question'
export const frameworkUrl = '/api/framework'
export const categoryUrl = '/api/category'
export const providerUrl = '/api/provider'
export const structureUrl = '/api/structure'
export const questionHierarchyUrl = '/api/questionhierarchy'
export const auth = '/auth'

export const rootQuestionRef = 'type'
export const cookieName = 'authorizationtoken'